import jakarat.servlet.ServletException;
import jakarta.servlet.annotation.WebServlet;
import jakarta.servlet.http.HttpServlet;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;

import java.io.IOException;
import java.io.PrintWriter;

@WebServlet("/hello");
class HelloServlet extends HttpServlet{
  @Override
  protected void doGet(HttpServletRequest request,
                       HttpServletResponse response)
  extends ServletException,IOException{
    response.setComtentType("text/html");
    PrintWriter out = response.getWriter();

    out.println("<html>");
    out.println("<body>");
    out.println("<h1>Hello from Servlet</h1>");
    out.println("<h2>Servlet Practical Using IntelliJ IDEA</h2>");
    out.println("<p>HTML Generated by Java Servlet</p>");
    out.println("</body>");
    out.println("</html>");
  }
}
